singer-io/tap-salesforce

- tap_salesforce/__init__.py
- tap_salesforce/salesforce.py
Fields that emit `selected-by-default` metadata will ultimately be selected unless specifically de-selected. With that said, unsupported fields should not be selected by default as the sync job will fail.
> move inclusion to metadata, do not select unsupported by default

- tap_salesforce/__init__.py
Added all of the unqueryable objects found in my testing.
I have added EntityDefinition to the blanket blacklist, but with a note that it only threw on the RecordTypesSupported field. If we add support to remove specific fields from discovery (instead of sync, like attributes), this could be made more granular.
> Update blacklisted objects

- tap_salesforce/__init__.py
- tap_salesforce/salesforce/__init__.py
- tap_salesforce/salesforce/bulk.py
Now logging:
- The name of the object that didn't completely sync in the case of tap termination due to quota.
- The amount of each API that was used per run.
- More verbose information on the amount of quota used/what allotted quota was hit on our side/etc in the case of tap termination due to quota.
> Adding more information around quota usage

- tap_salesforce/salesforce/__init__.py
We were missing the handling for a few types.
Primitive (https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/primitive_data_types.htm):
- byte
Field Types (https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/field_types.htm):
- calculated
- DataCategoryGroupReference (comes through as lowercase)
- masterrecord
> handle byte, calculated, datacategorygroupreference, and masterrecord types

- tap_salesforce/salesforce/__init__.py
It seems like picklists can be nil despite the metadata saying false.
> Set picklists to allow nill

- tap_salesforce/__init__.py
We have found cases where the Salesforce API will reference compound fields in their associated subfields' metadata but not provide them in the overall field list. In such cases, the tap will emit `unsupported` `inclusion` metadata but no schema entry. The proposed fix is to not emit `inclusion` when looping over the unsupported fields.
> do not emit metadata for unsupported fields if missing from field list

- tap_salesforce/salesforce/__init__.py
We've discovered that the `nillable` field on an Object's metadata does not mean anything valuable to our schema generation. Simply accept that any data can be nil except for our required Id field.
> Every field except Id can maybe be nil

- tap_salesforce/__init__.py
- tap_salesforce/salesforce/__init__.py
A little confusing, but this [Salesforce documentation](https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/compound_fields_limitations.htm#compound_fields_limitations) describes Location / Geolocation fields as also only queryable from REST / SOAP but it seems to work after testing.
> Only compound Address fields are unsupported by Bulk API

- tap_salesforce/salesforce/bulk.py
Depending on the Salesforce field, it is possible to copy/paste or enter NULL bytes `\0` into a Salesforce field. When output by the SF API, this data will poison the Python CSV reader with an error: 
```
csv.Error: line contains NULL byte
```
To fix this error, we can replace the null bytes with empty strings which will allow us to proceed without much modification to the data.
To find null bytes in the data, you can use sed piped to cat: `sed -n '/\x0/p' data.csv | cat -v`
> Replace null bytes with '' when encountered in the SF data

- tap_salesforce/salesforce/__init__.py
Don't let an exception during the `POST` to kill the thread and prevent it from executing another login.
> Prevent exceptions during login from killing the thread

- tap_salesforce/salesforce/bulk.py
- tap_salesforce/sync.py
Fixes a few more issues:
* Add more logging to show how far along we've gotten
* Call `write_state` during the normal sync whenever we finish syncing a batch and remove it.
> Add more logging and save state during normal chunked bulk sync

- tap_salesforce/salesforce/bulk.py
Due to an issue where Salesforce was killing open connections, we're going to try reading the entire response into memory.
> Read the dataset into memory

- tap_salesforce/sync.py
This fixes a bug where the version could be 0 and it isn't used because 0 is `falsey`
> Allow a zero to be a stream version

- tap_salesforce/salesforce/__init__.py
- tap_salesforce/salesforce/exceptions.py
- tap_salesforce/sync.py
Fixes a bug that looks like:
```
2018-02-07 10:09:47,268Z    tap -   File "/code/python3.5/site-packages/tap_salesforce/salesforce/exceptions.py", line 17, in __str__
2018-02-07 10:09:47,268Z    tap -     ", Response from Salesforce: {}".format(self.requestException.response.text)
2018-02-07 10:09:47,268Z    tap - AttributeError: 'str' object has no attribute 'response'
```
> Simplify error handling for http errors

- tap_salesforce/salesforce/__init__.py
Transform logic will attempt to parse the date and if that fails, just use the string.
> Use anyOf to help dates which can't format

- tap_salesforce/salesforce/bulk.py
Fixes some bad indentation of an error case where we'd be reassigning a variable.
> Fix improper indenation of error case

- tap_salesforce/salesforce/bulk.py
- tap_salesforce/sync.py
Custom tables can be PK chunked by their parent custom table:
For example:
i__Email__History
Can be PK Chunked by i__Email__c. The `find_parent` function was attempting to chunk by `i__Email__` which will cause an error.
> Add c to parent tables ending in __

- tap_salesforce/salesforce/bulk.py
The `OpportunityFieldHistory` export was failing since the `find_parent()` function was finding the suffix `History`, and returning the parent as `OpportunityField`.  
This PR adds a check for the suffix `FieldHistory` (before looking for `History`) so that `Opportunity` is correctly returned as the parent.
> add FieldHistory suffix to find_parent function

- .circleci/config.yml
- tap_salesforce/__init__.py
- tap_salesforce/salesforce/__init__.py
- tap_salesforce/salesforce/bulk.py
- tap_salesforce/salesforce/rest.py
- tap_salesforce/sync.py
This is due to an error received from the CSV decoder also mentioned in [this StackOverflow](https://stackoverflow.com/questions/15063936/csv-error-field-larger-than-field-limit-131072). This PR implements the accepted answer there.
**Note on the response to the accepted answer about this value not being valid for a C Integer:** Since this run on Python3, there is no longer a maximum Int value, so this shouldn't suffer from the same issue.
> Increase max size of CSV to system's max int

- tap_salesforce/__init__.py
- tap_salesforce/salesforce/bulk.py
- tap_salesforce/sync.py
If a sync runs incompletely, and saves a job ID that it was waiting on, then the Job isn't requested for some time, it will be deleted from Salesforce.
This PR is to detect this case, save bookmarks as-is, remove the JobID/BatchIDs from the state, then move on.
> Remove invalid job ids from state

- tap_salesforce/salesforce/rest.py
When a bulk REST query times out, the tap cuts the date range in half and tries again.  However, after syncing the records, the tap does not attempt to sync the second half of the original window.  
Since the tap only updates bookmarks when it gets records, in the event that no records are received in the first half of the date range, the bookmark will not advance, and the tap will never try to sync records in the second half of the date range.
This PR adds a check to see if the date range was chunked, and if it was, it queries the second half of the chunked date range.
> fix date chunking for bulk rest-api syncs

- tap_salesforce/sync.py
Every time the transformer closes its context, it logs the missing fields.  
Instead of creating a new transformer for each record, create a single one to transform all records.
> pull transformer outside of record write loop to minimize logging

- tap_salesforce/__init__.py
- tap_salesforce/salesforce/__init__.py
We've observed that Announcement returns this message when attempting to sync using a SOQL query.
```
InvalidBatch : Failed to process query: MALFORMED_QUERY: Implementation restriction: Announcement requires a filter by an ID, FeedItemId or ParentId using the equals operator.
```
This indicates that it isn't fit for replication without significant additions to the tap's structure (e.g., syncing it by `ParentId`, if it's possible to find a direct Parent link through the API). Because of this, the PR adds it to the blacklist, removing it from availability. See [Blacklisting.md](https://github.com/singer-io/tap-salesforce/blob/master/Blacklisting.md) for more info.
> Mark Announcement as query-incompatible

- tap_salesforce/salesforce/__init__.py
Turns out that response objects are always falsy if the status_code is >= 400. This PR extends our error handling code to add more info if the login raises an exception (e.g., inactive user)
> Put more information into error message for login failures

- tap_salesforce/__init__.py
- tap_salesforce/salesforce/bulk.py
- tap_salesforce/salesforce/exceptions.py
- tap_salesforce/salesforce/rest.py
Since `api_type` is immutable, the tap should fail during discovery if the user selected `BULK` but doesn't have permissions.  Otherwise, the tap fails during sync mode, and since the user cannot change `api_type`, they have to recreate the connection.
The fix is to try and check the bulk quota usage at the beginning of discovery, which returns a 403 if the user doesn't have `BULK` permissions.
> Query bulk during discovery

- .circleci/config.yml
Salesforce has a limit of 5 authorizations be user. So our integration tests, when run nightly would fail. The tests will now use a distinct user to run, so we are reinstating the nightly integration test runs.
- Checked to make sure that the credentials work in the latest master workflow run on Circle
Low, the tests are currently non-functional.
> Add nightly build

- tap_salesforce/__init__.py
Location data types are unsupported for the bulk API.  This PR adds those fields to the unsupported fields list.
-- Create a custom geolocation field in Salesforce
-- Create connection selecting all fields
-- Verify extraction completes without failure 
> Adding locations to unsupported fields

- tap_salesforce/salesforce/bulk.py
https://stitchdata.atlassian.net/browse/SRCE-2642
It seems that Bulk queries can fail with different messages than simply "timeout", this PR extends the functionality of PK Chunking to cover those situations.
- Ran through a low-volume sync (no pk chunking_ to check for syntax errors. Did not test logic.
Medium-low, the original case is still handled, but this may not fix all extraneous cases.
> Extend PK chunking to other failure messages

- tap_salesforce/__init__.py
https://stitchdata.atlassian.net/browse/SUP-1432
Add LoginEvent to the list of forced full table streams.
Low - key based replication for this stream does not work so forcing full table on it should be risk free. The forced-full table code is also preexisting so there should not be any risk in it.
> Force LoginEvent to do full table replication

- tap_salesforce/salesforce/__init__.py
According to the Salesforce docs, the DataType object does not support a LIMIT clause.
https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_datatype.htm
For now, we should mark this stream as unsupported until we modify how the tap issues queries.
> Add DataType stream to our QUERY_INCOMPATIBLE set

- tap_salesforce/salesforce/__init__.py
- tap_salesforce/sync.py
added NetworkUserHistoryRecent to blacklist
https://stitchdata.atlassian.net/secure/RapidBoard.jspa?rapidView=23&modal=detail&selectedIssue=SUP-1797
- ran discovery with cloned connection of  client that was previously getting an error that had to do with object not being supported. stream was no longer written to catalog
- low
> added NetworkUserHistoryRecent to blacklist

- setup.py
- tap_salesforce/sync.py
changed error message for `InvalidBatch : Failed to process query: OPERATION_TOO_LARGE: exceeded 100000 distinct who/what's` to be actionable, and wrapped it in a SingerSyncError. 
- manually raised exception with the same error message
low
> updated error message for OPERATION_TOO_LARGE

- tap_salesforce/salesforce/__init__.py
The tap encountered 
```InvalidBatch: Failed to process query:
BIG_OBJECT_UNSUPPORTED_OPERATION: Filters may not have any gaps within the composite key
```
The current shape of the WHERE + ORDER BY clauses:
```
WHERE replication_key >= some_date ORDER BY replication_key ASC
```
But `FieldHistoryArchive` seems to need something along these lines (note
CreatedDate is the replication key)
```
WHERE FieldHistoryType = 'ACCOUNT'
```
```
WHERE FieldHistoryType = 'ACCOUNT' AND CreatedDate >= 2020-01-01T00:00:00Z
```
```
WHERE FieldHistoryType = 'ACCOUNT' AND CreatedDate >= 2019-01-01T00:00:00Z
ORDER BY FieldHistoryType ASC, CreatedDate DESC
```
- Note the `DESC` here
This PR adds `FieldHistoryArchive` to the list of streams we don't support because it needs a different `WHERE` clause than the …
> Remove support for `FieldHistoryArchive`

- CHANGELOG.md
- setup.py
- tap_salesforce/salesforce/__init__.py
https://jira.talendforge.org/browse/TDL-9784
so the reason these processes were hanging for 24 hours is because in some rare cases the main thread would exit but a new timer thread would begin which would never be canceled and keep spawning a new thread for the rest of the 24 hours.
This pr makes the timer thread a daemon thread, which ensures that when the main thread exits the process will exit.
- low
> made timer thread a daemon thread

- spikes/test_threads.py
- tap_salesforce/salesforce/__init__.py
This PR
* Adds a spike to help understand how daemon threads should work
* Adds a timeout to all requests made by the tap
* Adds logging for the type of timeout that occurs
- I made requests to trigger a `ConnectTimeout` and `ReadTimeout` in order to know what errors to catch
- Low
> Fix login thread

- CHANGELOG.md
- setup.py
* Bumps Salesforce api from v41 to v52, this includes new streams and some permission changes on existing streams [#116](https://github.com/singer-io/tap-salesforce/pull/116)
> version bump v1.5.0 

- .circleci/config.yml
Increase the default timeout for no output 10 min -> 30 min.
> stabilize tests by increasing circleci timeout for no outpu

- .circleci/config.yml
https://jira.talendforge.org/browse/TDL-16944
Move build time to avoid conflicts with contractors and internal teams.
6:00am UTC -> 1:00 UTC (8:00pm EST, 6:30am IST)
Move slack notifications to new channel.
> move runtime and notifications

- tests/base.py
Use tap-tester logger in place of singer logger in tests
> use tap-tester logger in place of singer logger in tests

- tests/unittests/test_lookback_window.py
This PR adds unit tests to reflect how how we want `Salesforce.get_start_date()` to behave.
- We do not want to apply the lookback window to the start date
> Add failing unit tests

- .circleci/config.yml
- tap_salesforce/__init__.py
- tests/unittests/test_multiline_critical_error_message.py
TDL-7301: Handle multiline `CRITICAL` error messages
- Updated code to add `CRITICAL` for multiline error messages
> TDL-7301: Handle multiline `CRITICAL` error messages

- .circleci/config.yml
- tap_salesforce/sync.py
- tests/unittests/test_salesforce_null_bookmark.py
- Write unit test reproduce scenario where Full Table write bookmark with null key
- Resolved Full Table bookmarking with null key state
> TDL-16006: Fix interruptible full table bookmarking strategy for bulk API

- .circleci/config.yml
- README.md
- tap_salesforce/__init__.py
- tap_salesforce/salesforce/__init__.py
- tap_salesforce/salesforce/bulk.py
- tap_salesforce/salesforce/rest.py
- tap_salesforce/sync.py
- tests/test_salesforce_lookback_window.py
- tests/unittests/test_lookback_window.py
- tests/unittests/test_multiline_critical_error_message.py
- tests/unittests/test_salesforce_date_windowing.py
- tests/unittests/test_salesforce_null_bookmark.py
(write a short description here or paste a link to JIRA)
- #135 
- #137 
- #138 
- #140 
> Crest Work

- CHANGELOG.md
- setup.py
- tap_salesforce/__init__.py
- tests/base.py
This PR fixes the primary key for the `LightningUriEvent` Stream to make what Salesforce Docs says is the unique identifier of the event.
- PK changes require a major version bump
> TDL-23556 Update PKs

- tests/sfbase.py
- tests/test_salesforce_switch_rep_method_ft_incrmntl.py
- tests/test_salesforce_switch_rep_method_incrmntl_ft.py
Switching replication method from full_table to incremental and vice versa
low
> Switch replication methods
