singer-io/tap-salesforce

- README.md
- circle.yml
- tap_salesforce/__init__.py
- tap_salesforce/salesforce/__init__.py
- tap_salesforce/salesforce/bulk.py
- tap_salesforce/salesforce/exceptions.py
- tap_salesforce/salesforce/rest.py
Updating files according to some pylint, adding circle and readme.
> Pylint; Circle CI; README

- README.md
- tap_salesforce/salesforce/__init__.py
Addresses issue raised by [26](https://github.com/singer-io/tap-salesforce/issues/26)
> Adding start_date validation and better select_fields_by_default parsing

- tap_salesforce/salesforce/__init__.py
- tap_salesforce/salesforce/exceptions.py
Simplify the exception handling some more
> Bubble the requests exception

- .circleci/config.yml
- setup.py
- tap_salesforce/salesforce/__init__.py
Requires updated singer-python (pending PR: singer-io/singer-python#79)
> Use should_sync_field from singer

- setup.py
This change is in response to [CVE 2018-18074](https://cve.mitre.org/cgi-bin/cvename.cgi?name=2018-18074).
> Update version of requests

- CHANGELOG.md
- setup.py
PR to include the changes from #75 in version 1.4.30
- N/A, version bump
Low, it's a minor change within the framework of existing code.
- revert #75 and bump the minor version again
> Version 1.4.30 and changelog

- CHANGELOG.md
- setup.py
Version bump for #76 
- N/A
Low, this is a standard version bump
- revert #76, bump patch version, re-release
> Version 1.4.31 and changelog

- CHANGELOG.md
- setup.py
> Bump to v1.4.32

- CHANGELOG.md
- setup.py
bumped patch version to 1.4.34
- low
> bumped patch version to 1.4.34

- README.md
I had to do some research on Google to find out about `"is_sandbox": true`. I believe this is an important parameter to know about when running this tap, and deserves to be mentioned in the `README`.
No tests required
No risks
> Update README to inform about `is_sandbox`

- tests/test_salesforce_automatic_fields.py
> automatic fields test

- tap_salesforce/sync.py
> changed exception strings

- CHANGELOG.md
- setup.py
> Bump to v1.4.37, update changelog

- tests/base.py
> comment out the missing stream

- CHANGELOG.md
- setup.py
Bump to v1.4.39, update changelog
- See #114 
See #114 
- revert #114 and bump the version
> Bump to v1.4.39, update changelog

- .circleci/config.yml
Remove the pylint step for tap-tester.
> remove test pylint step

- CHANGELOG.md
- setup.py
(write a short description here or paste a link to JIRA)
None
> Version Bump to 1.5.1 and Changelog update

- tests/base.py
- tests/test_salesforce_activate_version_messages.py
- tests/test_salesforce_automatic_fields.py
- tests/test_salesforce_bookmarks.py
- tests/test_salesforce_discovery.py
- tests/test_salesforce_start_date.py
- tests/test_salesforce_sync_canary.py
Skipping all tests until we have a new test instance. 
> skip all tests

- README.md
Updates the readme to address [issue 105](https://github.com/singer-io/tap-salesforce/issues/105).
None.
> Updates a link to the singer-spec in the readme.

- .circleci/config.yml
- tap_salesforce/salesforce/__init__.py
- tap_salesforce/salesforce/bulk.py
- tap_salesforce/salesforce/rest.py
- tests/unittests/test_salesforce_date_windowing.py
- Add a Date windowing mechanism with a maximum retry of 4 for bulk API call
- Verify that with pk chunking and with date windowing we get the same sync output in bulk API call
> TDL-15349 Add Date Windowing

- tests/base.py
Account for new and removed streams from test account.
> update streams based on test account changes

- tests/base.py
Update test expectations for discovery mode to include AI streams that were added back to test account.
> updated expectations for AI streams

- .circleci/config.yml
- tests/base.py
- tests/test_salesforce_discovery_rest.py
- tests/test_salesforce_start_date.py
Save test logs as artifacts. Use tap-tester logger.
> save test artifacts

- tests/base.py
Add missing streams and associated metadata to base.py to account for newly reported streams for the bulk discovery test.
> Add / modify streams for discovery test

- tests/base.py
Update base to match what is currently being returned from API (again)
> Update base to match what is currently being returned from API (again)

- .circleci/config.yml
- tap_salesforce/sync.py
- tests/base.py
Add newly discovered stream to base
> Add newly discovered stream to base

- tests/base.py
New fields found in discovery April 2023
> New fields found in discovery April 2023

- tests/test_salesforce_full_table_replication.py
(write a short description here or paste a link to JIRA)
> Implement full table replication tests

- tests/base.py
Update discovery streams, June 2023
> Update discovery streams, June 2023

- tests/test_salesforce_sync_canary.py
> TDL-23608 Partition found_catalogs by weekday to save time and quota

- tests/base.py
- tests/sfbase.py
Add custom objects to expected metadata
> Add custom object to saleseforce account and update base to match

- tests/base.py
- tests/sfbase.py
- tests/test_custom_objects_bulk.py
- tests/test_custom_objects_rest.py
- tests/test_salesforce_sync_canary.py
> Verify tap can replicate all fields from new custom object stream

- tests/test_table_reset.py
> changes to table_reset

- tests/base.py
- tests/sfbase.py
- tests/test_salesforce_api_per_run_quota.py
- tests/test_salesforce_api_total_quota.py
- tests/test_salesforce_sync_canary.py
To add the new streams to the base files.
low
> Add newly discovered streams to the metadata

- .circleci/config.yml
Updates Cron schedule to only run on weekend to prevent quota limit from being used up
> Updates Cron schedule 

- .circleci/config.yml
https://qlik-dev.atlassian.net/browse/SAC-28311
https://internal.qlik.dev/general/ways-of-working/code-reviews/#guidelines-for-ai-generated-code
> SAC-28311: update circle config to use uv
